### ISSUE TITLE
Diagrams in a workspace not loaded

### ISSUE THREAD

**Issue by martinnec** [datagov-cz/ontoGrapher#395]
1. Create a workspace with three vocabularies: https://slovník.gov.cz/datový/registr-silničních-vozidel , https://slovník.gov.cz/agendový/998 , https://slovník.gov.cz/legislativní/sbírka/56/2001
2. Open in OG (reload if empty diagrams were loaded, see #393)
3. Diagrams are loaded but loading is not finished. There is an error in the console:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'labels')
    at sn (main.3a8a4de2.chunk.js:1:75120)
    at cn (main.3a8a4de2.chunk.js:1:76165)
    at jn (main.3a8a4de2.chunk.js:1:82457)
    at main.3a8a4de2.chunk.js:1:280479
    at l (2.110188c3.chunk.js:2:1424287)
    at Generator._invoke (2.110188c3.chunk.js:2:1424075)
    at Generator.next (2.110188c3.chunk.js:2:1424716)
    at r (2.110188c3.chunk.js:2:181909)
    at s (2.110188c3.chunk.js:2:182112)
```

**Comment by bindeali** [comment]
Closing as this seems to be fixed.
